import * as fs from 'fs';
import * as path from 'path';
import type { AppProduct, AppStore, AppPriceEntry } from '../mappers/toAppTypes.js';

export function generateSuperMarketsTs(
  stores: AppStore[],
  products: AppProduct[],
  prices: AppPriceEntry[],
  scrapeDate: string
): string {
  const lines: string[] = [];

  lines.push(`// Auto-generated by e-katanalotis crawler on ${scrapeDate}`);
  lines.push(`// Source: https://e-katanalotis.gov.gr/householdBasket`);
  lines.push(`// Do not edit manually - run 'npm run crawl:basket' to update`);
  lines.push(``);
  lines.push(`import { Store, Product, PriceEntry } from '../types';`);
  lines.push(``);

  // Stores
  lines.push(`// Greek Supermarket Chains`);
  lines.push(`export const stores: Store[] = [`);
  for (const store of stores) {
    const loc = store.location ? `, location: '${esc(store.location)}'` : '';
    lines.push(`  { id: '${esc(store.id)}', name: '${esc(store.name)}', nameGreek: '${esc(store.nameGreek)}', chain: '${esc(store.chain)}'${loc} },`);
  }
  lines.push(`];`);
  lines.push(``);

  // Products
  lines.push(`// Products from e-Katanalotis household basket`);
  lines.push(`export const products: Product[] = [`);

  // Group by category
  const byCategory = new Map<string, AppProduct[]>();
  for (const p of products) {
    const cat = p.category || 'General';
    if (!byCategory.has(cat)) byCategory.set(cat, []);
    byCategory.get(cat)!.push(p);
  }

  for (const [category, categoryProducts] of byCategory) {
    lines.push(`  // ${category}`);
    for (const p of categoryProducts) {
      const brand = p.brand ? `, brand: '${esc(p.brand)}'` : '';
      lines.push(`  { id: '${esc(p.id)}', name: '${esc(p.name)}', nameGreek: '${esc(p.nameGreek)}', category: '${esc(category)}'${brand}, unit: '${esc(p.unit)}' },`);
    }
  }
  lines.push(`];`);
  lines.push(``);

  // Prices
  lines.push(`// Prices from e-Katanalotis (EUR)`);
  lines.push(`export const prices: PriceEntry[] = [`);

  // Group by product for readability
  const byProduct = new Map<string, AppPriceEntry[]>();
  for (const price of prices) {
    if (!byProduct.has(price.productId)) byProduct.set(price.productId, []);
    byProduct.get(price.productId)!.push(price);
  }

  for (const [productId, productPrices] of byProduct) {
    const product = products.find((p) => p.id === productId);
    lines.push(`  // ${product?.name || productId}`);
    for (const price of productPrices) {
      const promo = price.promotion ? `, promotion: '${esc(price.promotion)}'` : '';
      lines.push(`  { productId: '${esc(price.productId)}', storeId: '${esc(price.storeId)}', price: ${price.price}, currency: '${esc(price.currency)}', lastUpdated: '${esc(price.lastUpdated)}'${promo} },`);
    }
  }
  lines.push(`];`);
  lines.push(``);

  // Helper functions (preserved from original)
  lines.push(`// Helper functions`);
  lines.push(`export function getProductById(id: string): Product | undefined {`);
  lines.push(`  return products.find(p => p.id === id);`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export function getStoreById(id: string): Store | undefined {`);
  lines.push(`  return stores.find(s => s.id === id);`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export function getPricesForProduct(productId: string): PriceEntry[] {`);
  lines.push(`  return prices.filter(p => p.productId === productId);`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export function findCheapestPrice(productId: string): PriceEntry | undefined {`);
  lines.push(`  const productPrices = getPricesForProduct(productId);`);
  lines.push(`  return productPrices.reduce((min, p) => p.price < min.price ? p : min, productPrices[0]);`);
  lines.push(`}`);
  lines.push(``);

  return lines.join('\n');
}

export function writeSuperMarketsTs(
  stores: AppStore[],
  products: AppProduct[],
  prices: AppPriceEntry[],
  scrapeDate: string,
  outputPath: string
): void {
  const content = generateSuperMarketsTs(stores, products, prices, scrapeDate);
  const dir = path.dirname(outputPath);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(outputPath, content, 'utf-8');
  console.log(`Written ${outputPath} (${stores.length} stores, ${products.length} products, ${prices.length} prices)`);
}

export function writeJsonOutput(
  stores: AppStore[],
  products: AppProduct[],
  prices: AppPriceEntry[],
  scrapeDate: string,
  outputPath: string
): void {
  const data = {
    scrapedAt: scrapeDate,
    metadata: {
      totalStores: stores.length,
      totalProducts: products.length,
      totalPriceEntries: prices.length,
    },
    stores,
    products,
    prices,
  };

  const dir = path.dirname(outputPath);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(outputPath, JSON.stringify(data, null, 2), 'utf-8');
  console.log(`Written ${outputPath}`);
}

function esc(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}
