import React, { useMemo, useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  TextInput,
  SafeAreaView,
  Modal,
  Platform,
} from 'react-native';
import { useTranslation } from 'react-i18next';
import { Ionicons } from '@expo/vector-icons';

import { products } from '../data/superMarkets';
import {
  allStores,
  getFacts,
  listTopCategories,
  ProductFacts,
} from '../services/priceIndex';
import { Store } from '../types';

// ============================================================================
// Historical snapshot baselines
// ----------------------------------------------------------------------------
// Generated by scripts/snapshot.sh whenever a new crawl runs. For now we
// hand-maintain entries here — each snapshot's date + per-store average price.
// Future work: auto-generate this from data/snapshots/* via a small build step.
// ============================================================================

interface HistoricalAvg {
  date: string;
  avgByStoreId: Record<string, number>;
}

const HISTORY: HistoricalAvg[] = [
  {
    date: '2026-05-24',
    avgByStoreId: {
      ab: 4.0799,
      bazaar: 3.3743,
      efresh: 4.3763,
      galaxias: 3.6830,
      halkiadakis: 3.9701,
      lidl: 4.0697,
      marketin: 3.3012,
      masoutis: 4.2607,
      mymarket: 3.8812,
      sklavenitis: 3.6233,
    },
  },
];

const PREV = HISTORY[HISTORY.length - 1];

// ============================================================================
// Live stats computed once at module load
// ============================================================================

interface ChainStat {
  store: Store;
  wins: number;
  avgPrice: number;
  productsStocked: number;
  /** Δ vs the previous snapshot in €, or null if no baseline. */
  delta: number | null;
}

interface DealRow {
  facts: ProductFacts;
  spread: number;
  spreadPercent: number;
}

interface OverallStats {
  totalProducts: number;
  totalChains: number;
  totalPriceEntries: number;
  avgPrice: number;
  /** Average overall price during the previous snapshot (weighted by chain). */
  prevAvgPrice: number | null;
}

const allFacts: ProductFacts[] = products
  .map((p) => getFacts(p.id))
  .filter((f): f is ProductFacts => f !== undefined && f.sortedPrices.length > 0);

const chainStats: ChainStat[] = (() => {
  const wins = new Map<string, number>();
  const sums = new Map<string, { sum: number; count: number }>();
  for (const s of allStores) {
    wins.set(s.id, 0);
    sums.set(s.id, { sum: 0, count: 0 });
  }
  for (const f of allFacts) {
    if (f.cheapest) wins.set(f.cheapest.store.id, (wins.get(f.cheapest.store.id) ?? 0) + 1);
    for (const sp of f.sortedPrices) {
      const e = sums.get(sp.store.id);
      if (e) {
        e.sum += sp.price;
        e.count += 1;
      }
    }
  }
  return allStores
    .map((store) => {
      const e = sums.get(store.id)!;
      const avgPrice = e.count ? e.sum / e.count : 0;
      const prev = PREV?.avgByStoreId[store.id];
      return {
        store,
        wins: wins.get(store.id) ?? 0,
        avgPrice,
        productsStocked: e.count,
        delta: typeof prev === 'number' ? avgPrice - prev : null,
      };
    })
    .sort((a, b) => b.wins - a.wins);
})();

const overallStats: OverallStats = (() => {
  let totalPriceEntries = 0;
  let priceSum = 0;
  for (const f of allFacts) {
    totalPriceEntries += f.storeCount;
    for (const sp of f.sortedPrices) priceSum += sp.price;
  }
  const avgPrice = totalPriceEntries ? priceSum / totalPriceEntries : 0;

  let prevAvgPrice: number | null = null;
  if (PREV) {
    // Weight previous avg by the number of entries each store currently has,
    // so the comparison is apples-to-apples even if catalog size shifted.
    let prevSum = 0;
    let prevCount = 0;
    for (const cs of chainStats) {
      const prev = PREV.avgByStoreId[cs.store.id];
      if (typeof prev === 'number') {
        prevSum += prev * cs.productsStocked;
        prevCount += cs.productsStocked;
      }
    }
    prevAvgPrice = prevCount ? prevSum / prevCount : null;
  }
  return {
    totalProducts: allFacts.length,
    totalChains: allStores.length,
    totalPriceEntries,
    avgPrice,
    prevAvgPrice,
  };
})();

const topDeals: DealRow[] = allFacts
  .filter((f) => f.sortedPrices.length >= 2 && f.cheapest && f.priciest)
  .map((f) => {
    const spread = f.priciest!.price - f.cheapest!.price;
    const spreadPercent = (spread / f.cheapest!.price) * 100;
    return { facts: f, spread, spreadPercent };
  })
  .sort((a, b) => b.spread - a.spread)
  .slice(0, 50);

const topCategories = listTopCategories();

// ============================================================================
// Helpers
// ============================================================================

function stripDiacritics(s: string): string {
  return s.toLowerCase().normalize('NFD').replace(/\p{Diacritic}/gu, '');
}

function averagesForCategory(category: string): ChainStat[] {
  const inCat = allFacts.filter(
    (f) => f.enriched?.categoryClean?.startsWith(category + '/')
  );
  const sums = new Map<string, { sum: number; count: number; wins: number }>();
  for (const s of allStores) sums.set(s.id, { sum: 0, count: 0, wins: 0 });
  for (const f of inCat) {
    if (f.cheapest) {
      const e = sums.get(f.cheapest.store.id);
      if (e) e.wins += 1;
    }
    for (const sp of f.sortedPrices) {
      const e = sums.get(sp.store.id);
      if (e) {
        e.sum += sp.price;
        e.count += 1;
      }
    }
  }
  return allStores
    .map((store) => {
      const e = sums.get(store.id)!;
      return {
        store,
        wins: e.wins,
        avgPrice: e.count ? e.sum / e.count : 0,
        productsStocked: e.count,
        delta: null,
      };
    })
    .filter((s) => s.productsStocked > 0)
    .sort((a, b) => a.avgPrice - b.avgPrice);
}

// ============================================================================
// Screen
// ============================================================================

export default function PriceTrackerScreen() {
  const { t, i18n } = useTranslation();
  const lang = i18n.language;
  const storeName = (s: Store) => (lang === 'el' ? s.nameGreek : s.name);

  const [search, setSearch] = useState('');
  const [category, setCategory] = useState<string | null>(null);
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [trendOpen, setTrendOpen] = useState(false);

  const currentChainStats = useMemo(
    () => (category ? averagesForCategory(category) : chainStats),
    [category]
  );

  const filteredFacts = useMemo(() => {
    const q = stripDiacritics(search.trim());
    return allFacts
      .filter((f) => {
        if (category && !f.enriched?.categoryClean?.startsWith(category + '/')) {
          return false;
        }
        if (q.length === 0) return true;
        const hay = stripDiacritics(`${f.product.name} ${f.product.nameGreek}`);
        return hay.includes(q);
      })
      .sort((a, b) => (a.cheapest?.price ?? 0) - (b.cheapest?.price ?? 0));
  }, [search, category]);

  const filteredDeals = useMemo(() => {
    if (!category) return topDeals.slice(0, 10);
    return topDeals
      .filter((d) =>
        d.facts.enriched?.categoryClean?.startsWith(category + '/')
      )
      .slice(0, 10);
  }, [category]);

  // Overall delta (current avg − previous avg).
  const overallDelta =
    overallStats.prevAvgPrice !== null
      ? overallStats.avgPrice - overallStats.prevAvgPrice
      : null;

  return (
    <SafeAreaView style={styles.container}>
      {/* Compact white header matching the rest of the app */}
      <View style={styles.header}>
        <Text style={styles.title}>{t('priceTracker.title')}</Text>
      </View>

      <ScrollView contentContainerStyle={styles.scrollBody}>
        {/* Subtitle hint */}
        <Text style={styles.subtitle}>{t('priceTracker.subtitle')}</Text>

        {/* Overview stats */}
        <View style={styles.statsGrid}>
          <StatCard
            label={t('priceTracker.totalProducts')}
            value={overallStats.totalProducts.toLocaleString()}
          />
          <StatCard
            label={t('priceTracker.totalChains')}
            value={overallStats.totalChains.toString()}
          />
          <StatCard
            label={t('priceTracker.totalPrices')}
            value={overallStats.totalPriceEntries.toLocaleString()}
          />
          <StatCard
            label={t('priceTracker.avgPrice')}
            value={`€${overallStats.avgPrice.toFixed(2)}`}
          />
        </View>

        {/* Average price trend card (tappable to see per-store breakdown) */}
        <TouchableOpacity
          style={styles.section}
          activeOpacity={0.7}
          onPress={() => setTrendOpen(true)}
        >
          <View style={styles.trendCardHeader}>
            <View style={{ flex: 1 }}>
              <SectionTitle icon="trending-up" text={t('priceTracker.avgTrend')} />
              <Text style={styles.sectionHint}>
                {PREV
                  ? t('priceTracker.avgTrendHint', { date: PREV.date })
                  : t('priceTracker.avgTrendHintNoBaseline')}
              </Text>
            </View>
            <Text style={styles.trendCardChevron}>›</Text>
          </View>
          <View style={styles.trendCardBody}>
            <Text style={styles.trendCardValue}>
              €{overallStats.avgPrice.toFixed(2)}
            </Text>
            {overallDelta !== null && (
              <DeltaBadge value={overallDelta} />
            )}
          </View>
        </TouchableOpacity>

        {/* Category pills */}
        <View style={styles.catPillContainer}>
          <ScrollView
            horizontal
            showsHorizontalScrollIndicator={false}
            contentContainerStyle={styles.catPillRow}
          >
            <FilterPill
              label={t('priceTracker.all')}
              active={category === null}
              onPress={() => setCategory(null)}
            />
            {topCategories.map((c) => (
              <FilterPill
                key={c.name}
                label={`${c.name} (${c.count})`}
                active={category === c.name}
                onPress={() => setCategory(c.name)}
              />
            ))}
          </ScrollView>
        </View>

        {/* Chain leaderboard */}
        <View style={styles.section}>
          <SectionTitle
            icon="trophy"
            text={
              category
                ? `${t('priceTracker.chainAvgInCategory')} — ${category}`
                : t('priceTracker.chainLeaderboard')
            }
          />
          <Text style={styles.sectionHint}>
            {category
              ? t('priceTracker.chainAvgHint')
              : t('priceTracker.chainLeaderboardHint')}
          </Text>
          <View style={styles.chainList}>
            {currentChainStats.map((cs, i) => {
              const maxMetric = category
                ? Math.max(...currentChainStats.map((x) => x.avgPrice), 0.01)
                : Math.max(...currentChainStats.map((x) => x.wins), 1);
              const widthPct = category
                ? Math.max(8, 100 - (cs.avgPrice / maxMetric) * 80)
                : (cs.wins / maxMetric) * 100;
              return (
                <View key={cs.store.id} style={styles.chainRow}>
                  <View style={styles.chainLabelCol}>
                    <Text style={styles.chainRank}>
                      {i === 0 ? '🏆 ' : `${i + 1}. `}
                      {storeName(cs.store)}
                    </Text>
                    <Text style={styles.chainMeta}>
                      {category
                        ? t('priceTracker.avgIn', {
                            count: cs.productsStocked,
                          })
                        : t('priceTracker.winsIn', {
                            wins: cs.wins,
                            stocked: cs.productsStocked,
                          })}
                    </Text>
                  </View>
                  <View style={styles.chainBarTrack}>
                    <View
                      style={[
                        styles.chainBarFill,
                        {
                          width: `${widthPct}%`,
                          backgroundColor: i === 0 ? '#4caf50' : '#90caf9',
                        },
                      ]}
                    />
                  </View>
                  <Text style={styles.chainMetricValue}>
                    {category ? `€${cs.avgPrice.toFixed(2)}` : cs.wins}
                  </Text>
                </View>
              );
            })}
          </View>
        </View>

        {/* Top deals */}
        {filteredDeals.length > 0 && (
          <View style={styles.section}>
            <SectionTitle icon="cash-outline" text={t('priceTracker.topDeals')} />
            <Text style={styles.sectionHint}>
              {t('priceTracker.topDealsHint')}
            </Text>
            {filteredDeals.map((d) => {
              const p = d.facts;
              const name = lang === 'el' ? p.product.nameGreek : p.product.name;
              return (
                <View key={p.product.id} style={styles.dealRow}>
                  <View style={styles.dealTextCol}>
                    <Text style={styles.dealName} numberOfLines={2}>
                      {name}
                    </Text>
                    <Text style={styles.dealSubtext}>
                      €{p.cheapest!.price.toFixed(2)} @ {storeName(p.cheapest!.store)}
                      {'  ·  '}
                      €{p.priciest!.price.toFixed(2)} @ {storeName(p.priciest!.store)}
                    </Text>
                  </View>
                  <View style={styles.dealSavingsCol}>
                    <Text style={styles.dealSavings}>
                      −€{d.spread.toFixed(2)}
                    </Text>
                    <Text style={styles.dealSavingsPct}>
                      −{d.spreadPercent.toFixed(0)}%
                    </Text>
                  </View>
                </View>
              );
            })}
          </View>
        )}

        {/* Search + table */}
        <View style={styles.section}>
          <SectionTitle icon="search" text={t('priceTracker.fullPriceTable')} />
          <TextInput
            style={styles.searchInput}
            placeholder={t('priceTracker.searchPlaceholder')}
            placeholderTextColor="#999"
            value={search}
            onChangeText={setSearch}
            autoCorrect={false}
          />
          <Text style={styles.tableSummary}>
            {t('priceTracker.showingResults', { count: filteredFacts.length })}
          </Text>
          {filteredFacts.length === 0 ? (
            <View style={styles.emptyState}>
              <Text style={styles.emptyText}>{t('priceTracker.noResults')}</Text>
            </View>
          ) : (
            filteredFacts.slice(0, 100).map((f) => {
              const name = lang === 'el' ? f.product.nameGreek : f.product.name;
              const isExpanded = expandedId === f.product.id;
              const spread = f.priciest && f.cheapest ? f.priciest.price - f.cheapest.price : 0;
              return (
                <View key={f.product.id} style={styles.productCard}>
                  <TouchableOpacity
                    onPress={() =>
                      setExpandedId((prev) => (prev === f.product.id ? null : f.product.id))
                    }
                    style={styles.productRow}
                    activeOpacity={0.7}
                  >
                    <Text style={styles.productChevron}>{isExpanded ? '▾' : '▸'}</Text>
                    <View style={{ flex: 1 }}>
                      <Text style={styles.productName} numberOfLines={2}>
                        {name}
                      </Text>
                      <Text style={styles.productSubtext}>
                        €{f.cheapest!.price.toFixed(2)} @ {storeName(f.cheapest!.store)}
                        {'  ·  '}
                        {f.storeCount} {t('priceTracker.stores')}
                        {spread > 0 && `  ·  ${t('priceTracker.spread')} €${spread.toFixed(2)}`}
                      </Text>
                    </View>
                  </TouchableOpacity>
                  {isExpanded && (
                    <View style={styles.productPrices}>
                      {f.sortedPrices.map((sp, i) => {
                        const delta = sp.price - f.cheapest!.price;
                        return (
                          <View
                            key={sp.store.id}
                            style={[
                              styles.priceLine,
                              i === 0 && styles.priceLineBest,
                            ]}
                          >
                            <Text style={styles.priceLineStore}>
                              {i === 0 ? '🏆 ' : ''}
                              {storeName(sp.store)}
                            </Text>
                            <View style={styles.priceLineRight}>
                              <Text style={styles.priceLineAmount}>
                                €{sp.price.toFixed(2)}
                              </Text>
                              {delta > 0 && (
                                <Text style={styles.priceLineDelta}>
                                  +€{delta.toFixed(2)}
                                </Text>
                              )}
                            </View>
                          </View>
                        );
                      })}
                    </View>
                  )}
                </View>
              );
            })
          )}
          {filteredFacts.length > 100 && (
            <Text style={styles.tableMore}>
              + {filteredFacts.length - 100} {t('priceTracker.more')}
            </Text>
          )}
        </View>
      </ScrollView>

      {/* Trend modal — per-chain avg + Δ vs previous snapshot */}
      <Modal
        visible={trendOpen}
        animationType="slide"
        transparent
        onRequestClose={() => setTrendOpen(false)}
      >
        <View style={styles.modalBackdrop}>
          <View style={styles.modalCard}>
            <View style={styles.modalHeader}>
              <View style={styles.modalTitleRow}>
                <Ionicons name="trending-up" size={18} color="#212121" style={{ marginRight: 8 }} />
                <Text style={styles.modalTitle}>
                  {t('priceTracker.avgTrend')}
                </Text>
              </View>
              <TouchableOpacity onPress={() => setTrendOpen(false)}>
                <Text style={styles.modalClose}>{t('basketClose')}</Text>
              </TouchableOpacity>
            </View>

            <ScrollView contentContainerStyle={styles.modalBody}>
              <Text style={styles.modalIntro}>
                {PREV
                  ? t('priceTracker.avgTrendModalHint', { date: PREV.date })
                  : t('priceTracker.avgTrendHintNoBaseline')}
              </Text>

              {/* Per-store bars sorted by current avg */}
              {[...chainStats]
                .sort((a, b) => a.avgPrice - b.avgPrice)
                .map((cs) => {
                  const maxAvg = Math.max(...chainStats.map((x) => x.avgPrice));
                  const widthPct = (cs.avgPrice / maxAvg) * 100;
                  const prev = PREV?.avgByStoreId[cs.store.id];
                  return (
                    <View key={cs.store.id} style={styles.trendStoreRow}>
                      <View style={styles.trendStoreLabel}>
                        <Text style={styles.trendStoreName}>
                          {storeName(cs.store)}
                        </Text>
                        {typeof prev === 'number' && (
                          <Text style={styles.trendStorePrev}>
                            {t('priceTracker.was')} €{prev.toFixed(2)}
                          </Text>
                        )}
                      </View>
                      <View style={styles.trendStoreBarTrack}>
                        <View
                          style={[
                            styles.trendStoreBarFill,
                            { width: `${widthPct}%` },
                          ]}
                        />
                      </View>
                      <View style={styles.trendStoreRight}>
                        <Text style={styles.trendStoreAvg}>
                          €{cs.avgPrice.toFixed(2)}
                        </Text>
                        {cs.delta !== null && <DeltaBadge value={cs.delta} small />}
                      </View>
                    </View>
                  );
                })}
            </ScrollView>
          </View>
        </View>
      </Modal>
    </SafeAreaView>
  );
}

// ============================================================================
// Sub-components
// ============================================================================

/** Section title with a leading Ionicon — used to replace the emoji prefix
 *  pattern (e.g. "🏆 Leaderboard") so every section header looks consistent. */
function SectionTitle({
  icon,
  text,
}: {
  icon: React.ComponentProps<typeof Ionicons>['name'];
  text: string;
}) {
  return (
    <View style={styles.sectionTitleRow}>
      <Ionicons name={icon} size={16} color="#37474f" style={styles.sectionTitleIcon} />
      <Text style={styles.sectionTitle}>{text}</Text>
    </View>
  );
}

function StatCard({ label, value }: { label: string; value: string }) {
  return (
    <View style={styles.statCard}>
      <Text style={styles.statLabel}>{label}</Text>
      <Text style={styles.statValue}>{value}</Text>
    </View>
  );
}

function FilterPill({
  label,
  active,
  onPress,
}: {
  label: string;
  active: boolean;
  onPress: () => void;
}) {
  return (
    <TouchableOpacity
      style={[styles.catPill, active && styles.catPillActive]}
      onPress={onPress}
    >
      <Text style={[styles.catPillText, active && styles.catPillTextActive]}>
        {label}
      </Text>
    </TouchableOpacity>
  );
}

function DeltaBadge({ value, small = false }: { value: number; small?: boolean }) {
  const isFlat = Math.abs(value) < 0.005;
  const isUp = value > 0;
  const colour = isFlat ? '#90a4ae' : isUp ? '#ef6c00' : '#2e7d32';
  const arrow = isFlat ? '→' : isUp ? '↑' : '↓';
  const formatted = `${arrow} €${Math.abs(value).toFixed(2)}`;
  return (
    <Text
      style={[
        small ? styles.deltaBadgeSmall : styles.deltaBadge,
        { color: colour },
      ]}
    >
      {formatted}
    </Text>
  );
}

// ============================================================================
// Styles — aligned with the ChatScreen design language: white background,
// flat header, light borders, no big colored banners.
// ============================================================================

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  scrollBody: {
    paddingBottom: 24,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
  },
  subtitle: {
    fontSize: 12,
    color: '#666',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 4,
  },
  // Stats grid
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 12,
    paddingTop: 8,
    gap: 8,
    justifyContent: 'space-between',
  },
  statCard: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 12,
    flexBasis: '48%',
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  statLabel: {
    fontSize: 11,
    color: '#666',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  statValue: {
    fontSize: 18,
    fontWeight: '700',
    color: '#212121',
  },
  // Trend card
  trendCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  trendCardChevron: {
    fontSize: 22,
    color: '#90a4ae',
    marginLeft: 8,
  },
  trendCardBody: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 12,
    marginTop: 8,
  },
  trendCardValue: {
    fontSize: 28,
    fontWeight: '700',
    color: '#212121',
  },
  deltaBadge: {
    fontSize: 14,
    fontWeight: '700',
  },
  deltaBadgeSmall: {
    fontSize: 11,
    fontWeight: '700',
  },
  // Category pills
  catPillContainer: {
    backgroundColor: '#fff',
    marginTop: 12,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#e0e0e0',
  },
  catPillRow: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 6,
  },
  catPill: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: '#eceff1',
    marginRight: 6,
  },
  catPillActive: {
    backgroundColor: '#4caf50',
  },
  catPillText: {
    fontSize: 12,
    color: '#37474f',
    fontWeight: '600',
  },
  catPillTextActive: {
    color: '#fff',
  },
  // Sections
  section: {
    backgroundColor: '#fff',
    margin: 12,
    marginBottom: 0,
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  sectionTitleIcon: {
    marginRight: 6,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#212121',
    marginBottom: 4,
  },
  modalTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sectionHint: {
    fontSize: 11,
    color: '#777',
    marginBottom: 10,
  },
  // Chain leaderboard
  chainList: {
    gap: 8,
  },
  chainRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  chainLabelCol: {
    flexBasis: 130,
  },
  chainRank: {
    fontSize: 12,
    fontWeight: '700',
    color: '#212121',
  },
  chainMeta: {
    fontSize: 10,
    color: '#777',
  },
  chainBarTrack: {
    flex: 1,
    height: 14,
    backgroundColor: '#eceff1',
    borderRadius: 7,
    overflow: 'hidden',
  },
  chainBarFill: {
    height: '100%',
    borderRadius: 7,
  },
  chainMetricValue: {
    width: 56,
    textAlign: 'right',
    fontSize: 13,
    fontWeight: '700',
    color: '#212121',
  },
  // Deals
  dealRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f5f5f5',
  },
  dealTextCol: {
    flex: 1,
    marginRight: 8,
  },
  dealName: {
    fontSize: 13,
    fontWeight: '600',
    color: '#212121',
  },
  dealSubtext: {
    fontSize: 11,
    color: '#666',
    marginTop: 2,
  },
  dealSavingsCol: {
    alignItems: 'flex-end',
  },
  dealSavings: {
    fontSize: 14,
    fontWeight: '700',
    color: '#2e7d32',
  },
  dealSavingsPct: {
    fontSize: 11,
    color: '#388e3c',
  },
  // Search + table
  searchInput: {
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 14,
    color: '#212121',
    marginBottom: 8,
  },
  tableSummary: {
    fontSize: 11,
    color: '#777',
    marginBottom: 8,
  },
  productCard: {
    borderBottomWidth: 1,
    borderBottomColor: '#f5f5f5',
  },
  productRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: 8,
  },
  productChevron: {
    width: 16,
    fontSize: 12,
    color: '#90a4ae',
    marginTop: 1,
  },
  productName: {
    fontSize: 13,
    color: '#212121',
  },
  productSubtext: {
    fontSize: 11,
    color: '#558b2f',
    marginTop: 2,
  },
  productPrices: {
    paddingLeft: 16,
    paddingBottom: 10,
    paddingRight: 4,
  },
  priceLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 6,
    marginBottom: 3,
    backgroundColor: '#fafafa',
  },
  priceLineBest: {
    backgroundColor: '#e8f5e9',
  },
  priceLineStore: {
    fontSize: 12,
    color: '#212121',
    flex: 1,
  },
  priceLineRight: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 8,
  },
  priceLineAmount: {
    fontSize: 13,
    fontWeight: '700',
    color: '#212121',
  },
  priceLineDelta: {
    fontSize: 11,
    color: '#ef6c00',
    marginLeft: 6,
  },
  tableMore: {
    textAlign: 'center',
    fontSize: 12,
    color: '#777',
    fontStyle: 'italic',
    marginTop: 8,
  },
  emptyState: {
    paddingVertical: 24,
    alignItems: 'center',
  },
  emptyText: {
    color: '#999',
    fontSize: 13,
  },
  // Modal (matches the basket modal styling so the whole app feels uniform)
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    height: '85%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#212121',
  },
  modalClose: {
    fontSize: 14,
    color: '#1976d2',
    fontWeight: '600',
  },
  modalBody: {
    padding: 16,
    paddingBottom: Platform.OS === 'android' ? 32 : 36,
  },
  modalIntro: {
    fontSize: 12,
    color: '#777',
    marginBottom: 14,
  },
  // Per-store trend row in the modal
  trendStoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f5f5f5',
  },
  trendStoreLabel: {
    flexBasis: 110,
  },
  trendStoreName: {
    fontSize: 12,
    fontWeight: '700',
    color: '#212121',
  },
  trendStorePrev: {
    fontSize: 10,
    color: '#999',
    marginTop: 2,
  },
  trendStoreBarTrack: {
    flex: 1,
    height: 10,
    backgroundColor: '#eceff1',
    borderRadius: 5,
    overflow: 'hidden',
  },
  trendStoreBarFill: {
    height: '100%',
    backgroundColor: '#4caf50',
    borderRadius: 5,
  },
  trendStoreRight: {
    alignItems: 'flex-end',
    width: 70,
  },
  trendStoreAvg: {
    fontSize: 14,
    fontWeight: '700',
    color: '#212121',
  },
});
