// Auto-generated by e-katanalotis crawler on 2026-03-16
// Source: https://e-katanalotis.gov.gr/householdBasket
// Do not edit manually - run 'npm run crawl:basket' to update

import { Store, Product, PriceEntry } from '../types';

// Greek Supermarket Chains
export const stores: Store[] = [
  { id: 'halkiadakis', name: 'Halkiadakis', nameGreek: 'Χαλκιαδάκης', chain: 'Halkiadakis' },
  { id: 'sklavenitis', name: 'Sklavenitis', nameGreek: 'Σκλαβενίτης', chain: 'Sklavenitis' },
  { id: 'masoutis', name: 'Masoutis', nameGreek: 'Μασούτης', chain: 'Masoutis' },
  { id: 'synka', name: 'Synka', nameGreek: 'Synka', chain: 'Synka' },
  { id: 'mymarket', name: 'My Market', nameGreek: 'My Market', chain: 'My Market' },
  { id: 'marketin', name: 'Market In', nameGreek: 'Market In', chain: 'Market In' },
  { id: 'galaxias', name: 'Galaxias', nameGreek: 'Γαλαξίας', chain: 'Galaxias' },
  { id: 'ab', name: 'AB Vasilopoulos', nameGreek: 'ΑΒ Βασιλόπουλος', chain: 'AB' },
  { id: 'efresh', name: 'eFresh', nameGreek: 'eFresh', chain: 'eFresh' },
];

// Products from e-Katanalotis household basket
export const products: Product[] = [
  // Meat
  { id: 'πινδος-κοτοπουλο-ελληνικο-νωποτιμ-κιλ', name: 'ΠΙΝΔΟΣ ΚΟΤΟΠΟΥΛΟ ΕΛΛΗΝΙΚΟ ΝΩΠΟ(ΤΙΜ. ΚΙΛ)', nameGreek: 'ΠΙΝΔΟΣ ΚΟΤΟΠΟΥΛΟ ΕΛΛΗΝΙΚΟ ΝΩΠΟ(ΤΙΜ. ΚΙΛ)', category: 'Meat', unit: 'pcs' },
  { id: 'πινδος-κοτοπ-ελληνικα-νω-τ-65-δισκτ-κ', name: 'ΠΙΝΔΟΣ ΚΟΤΟΠ. ΕΛΛΗΝΙΚΑ ΝΩ Τ. 65% ΔΙΣΚ(Τ. Κ)', nameGreek: 'ΠΙΝΔΟΣ ΚΟΤΟΠ. ΕΛΛΗΝΙΚΑ ΝΩ Τ. 65% ΔΙΣΚ(Τ. Κ)', category: 'Meat', unit: 'pcs' },
  { id: 'mimikos-κοτοπουλο-ελλην-νωπο-τ-65t-k', name: 'MIMIKOS ΚΟΤΟΠΟΥΛΟ ΕΛΛΗΝ. ΝΩΠΟ Τ. 65%(T. K)', nameGreek: 'MIMIKOS ΚΟΤΟΠΟΥΛΟ ΕΛΛΗΝ. ΝΩΠΟ Τ. 65%(T. K)', category: 'Meat', unit: 'pcs' },
  { id: 'αγγελακης-κοτοπ-ελλην-νωπο-δισκ-τ-κ', name: 'ΑΓΓΕΛΑΚΗΣ ΚΟΤΟΠ. ΕΛΛΗΝ. ΝΩΠΟ ΔΙΣΚ. (Τ. Κ)', nameGreek: 'ΑΓΓΕΛΑΚΗΣ ΚΟΤΟΠ. ΕΛΛΗΝ. ΝΩΠΟ ΔΙΣΚ. (Τ. Κ)', category: 'Meat', unit: 'pcs' },
  { id: 'μπριζολα-χοιρ-ολλανδ-νωπ-mο-xφτ-κ', name: 'ΜΠΡΙΖΟΛΑ ΧΟΙΡ. ΟΛΛΑΝΔ. ΝΩΠ. M/Ο X/Φ(Τ. Κ)', nameGreek: 'ΜΠΡΙΖΟΛΑ ΧΟΙΡ. ΟΛΛΑΝΔ. ΝΩΠ. M/Ο X/Φ(Τ. Κ)', category: 'Meat', unit: 'pcs' },
  { id: 'μπριζολα-χοιρ-ελλην-νωπη-mο-αδ-χφ-τ-κ', name: 'ΜΠΡΙΖΟΛΑ ΧΟΙΡ. ΕΛΛΗΝ. ΝΩΠΗ M/Ο Α/Δ Χ/Φ. Τ. Κ', nameGreek: 'ΜΠΡΙΖΟΛΑ ΧΟΙΡ. ΕΛΛΗΝ. ΝΩΠΗ M/Ο Α/Δ Χ/Φ. Τ. Κ', category: 'Meat', unit: 'pcs' },
  { id: 'χοιρινος-λαιμος-ολλανδιας-μοτιμη-κιλου', name: 'ΧΟΙΡΙΝΟΣ ΛΑΙΜΟΣ ΟΛΛΑΝΔΙΑΣ Μ/Ο(ΤΙΜΗ ΚΙΛΟΥ', nameGreek: 'ΧΟΙΡΙΝΟΣ ΛΑΙΜΟΣ ΟΛΛΑΝΔΙΑΣ Μ/Ο(ΤΙΜΗ ΚΙΛΟΥ', category: 'Meat', unit: 'kg' },
  { id: 'χοιρινος-λαιμος-μο-ελληνικοςτιμη-κιλ', name: 'ΧΟΙΡΙΝΟΣ ΛΑΙΜΟΣ Μ/Ο ΕΛΛΗΝΙΚΟΣ(ΤΙΜΗ ΚΙΛ)', nameGreek: 'ΧΟΙΡΙΝΟΣ ΛΑΙΜΟΣ Μ/Ο ΕΛΛΗΝΙΚΟΣ(ΤΙΜΗ ΚΙΛ)', category: 'Meat', unit: 'pcs' },
  { id: 'σπάλα-νεαρού-μοσχ-αο-νωπή-εις', name: 'ΣΠΆΛΑ ΝΕΑΡΟΎ ΜΟΣΧ Α/Ο ΝΩΠΉ ΕΙΣ', nameGreek: 'ΣΠΆΛΑ ΝΕΑΡΟΎ ΜΟΣΧ Α/Ο ΝΩΠΉ ΕΙΣ', category: 'Meat', unit: 'pcs' },
  { id: 'κιλοτο-μοσχου-γαλακτος-ολλανδιας-τ-κ', name: 'ΚΙΛΟΤΟ ΜΟΣΧΟΥ ΓΑΛΑΚΤΟΣ ΟΛΛΑΝΔΙΑΣ Τ. Κ.', nameGreek: 'ΚΙΛΟΤΟ ΜΟΣΧΟΥ ΓΑΛΑΚΤΟΣ ΟΛΛΑΝΔΙΑΣ Τ. Κ.', category: 'Meat', unit: 'kg' },
  { id: 'λάπα-νεαρού-μοσχ-αο-νωπή-εις', name: 'ΛΆΠΑ ΝΕΑΡΟΎ ΜΟΣΧ Α/Ο ΝΩΠΉ ΕΙΣ', nameGreek: 'ΛΆΠΑ ΝΕΑΡΟΎ ΜΟΣΧ Α/Ο ΝΩΠΉ ΕΙΣ', category: 'Meat', unit: 'pcs' },
  { id: 'ελιά-νεαρού-μοσχ-αο-νωπή-εις', name: 'ΕΛΙΆ ΝΕΑΡΟΎ ΜΟΣΧ Α/Ο ΝΩΠΉ ΕΙΣ', nameGreek: 'ΕΛΙΆ ΝΕΑΡΟΎ ΜΟΣΧ Α/Ο ΝΩΠΉ ΕΙΣ', category: 'Meat', unit: 'pcs' },
  // General
  { id: 'νιτσιακος-κοτ-ελληνικα-νωπα-δισκτ-κιλ', name: 'ΝΙΤΣΙΑΚΟΣ ΚΟΤ. ΕΛΛΗΝΙΚΑ ΝΩΠΑ ΔΙΣΚ(Τ. ΚΙΛ)', nameGreek: 'ΝΙΤΣΙΑΚΟΣ ΚΟΤ. ΕΛΛΗΝΙΚΑ ΝΩΠΑ ΔΙΣΚ(Τ. ΚΙΛ)', category: 'General', unit: 'pcs' },
  { id: 'πινδος-φιλετο-στηθος-κοτ-ελλ-νωπο-τ-κ', name: 'ΠΙΝΔΟΣ ΦΙΛΕΤΟ ΣΤΗΘΟΣ ΚΟΤ. ΕΛΛ. ΝΩΠΟ (Τ. Κ. )', nameGreek: 'ΠΙΝΔΟΣ ΦΙΛΕΤΟ ΣΤΗΘΟΣ ΚΟΤ. ΕΛΛ. ΝΩΠΟ (Τ. Κ. )', category: 'General', unit: 'pcs' },
  { id: 'mimikos-στηθος-φιλ-κοτ-ελλην-νωπο-650g', name: 'MIMIKOS ΣΤΗΘΟΣ ΦΙΛ. ΚΟΤ. ΕΛΛΗΝ. ΝΩΠΟ 650G', nameGreek: 'MIMIKOS ΣΤΗΘΟΣ ΦΙΛ. ΚΟΤ. ΕΛΛΗΝ. ΝΩΠΟ 650G', category: 'General', unit: 'pcs' },
  { id: 'αρνια-ελληνικα-τimh-κιλοy', name: 'ΑΡΝΙΑ ΕΛΛΗΝΙΚΑ (ΤIMH ΚΙΛΟY)', nameGreek: 'ΑΡΝΙΑ ΕΛΛΗΝΙΚΑ (ΤIMH ΚΙΛΟY)', category: 'General', unit: 'kg' },
  { id: 'κατσικια-ελληνικα-τimh-κιλοy', name: 'ΚΑΤΣΙΚΙΑ ΕΛΛΗΝΙΚΑ (ΤIMH ΚΙΛΟY)', nameGreek: 'ΚΑΤΣΙΚΙΑ ΕΛΛΗΝΙΚΑ (ΤIMH ΚΙΛΟY)', category: 'General', unit: 'kg' },
  { id: 'λουμιδης-πaπaγaλoς-παραδος-981γ', name: 'ΛΟΥΜΙΔΗΣ ΠAΠAΓAΛOΣ ΠΑΡΑΔΟΣ 981Γ', nameGreek: 'ΛΟΥΜΙΔΗΣ ΠAΠAΓAΛOΣ ΠΑΡΑΔΟΣ 981Γ', category: 'General', unit: 'pcs' },
  { id: 'μπουτι-χοιρ-ολλαν-νωπο-αο-αδτ-κ', name: 'ΜΠΟΥΤΙ ΧΟΙΡ. ΟΛΛΑΝ. ΝΩΠΟ Α/Ο Α/Δ(Τ. Κ)', nameGreek: 'ΜΠΟΥΤΙ ΧΟΙΡ. ΟΛΛΑΝ. ΝΩΠΟ Α/Ο Α/Δ(Τ. Κ)', category: 'General', unit: 'pcs' },
  { id: 'μπουτι-χοιρ-ελληνικο-νωπο-αοτιμη-κιλ', name: 'ΜΠΟΥΤΙ ΧΟΙΡ. ΕΛΛΗΝΙΚΟ ΝΩΠΟ Α/Ο(ΤΙΜΗ ΚΙΛ)', nameGreek: 'ΜΠΟΥΤΙ ΧΟΙΡ. ΕΛΛΗΝΙΚΟ ΝΩΠΟ Α/Ο(ΤΙΜΗ ΚΙΛ)', category: 'General', unit: 'pcs' },
  { id: 'σπαλα-βοειου-γερμαν-νωπη-αο-τιμ-κιλ', name: 'ΣΠΑΛΑ ΒΟΕΙΟΥ ΓΕΡΜΑΝ. ΝΩΠΗ Α/Ο (ΤΙΜ. ΚΙΛ).', nameGreek: 'ΣΠΑΛΑ ΒΟΕΙΟΥ ΓΕΡΜΑΝ. ΝΩΠΗ Α/Ο (ΤΙΜ. ΚΙΛ).', category: 'General', unit: 'pcs' },
  { id: 'βοειον-σπαλα-ελληνικο-αοκιλονωπο', name: 'ΒΟΕΙΟΝ ΣΠΑΛΑ ΕΛΛΗΝΙΚΟ Α/Ο(ΚΙΛΟ)ΝΩΠΟ', nameGreek: 'ΒΟΕΙΟΝ ΣΠΑΛΑ ΕΛΛΗΝΙΚΟ Α/Ο(ΚΙΛΟ)ΝΩΠΟ', category: 'General', unit: 'kg' },
  { id: 'κιλοτο-βοειου-γερμανιας-νωπο-αοτ-κιλ', name: 'ΚΙΛΟΤΟ ΒΟΕΙΟΥ ΓΕΡΜΑΝΙΑΣ ΝΩΠΟ Α/Ο(Τ. ΚΙΛ)', nameGreek: 'ΚΙΛΟΤΟ ΒΟΕΙΟΥ ΓΕΡΜΑΝΙΑΣ ΝΩΠΟ Α/Ο(Τ. ΚΙΛ)', category: 'General', unit: 'kg' },
  { id: 'βοειον-κιλοτο-ελληνικο-νωπο', name: 'ΒΟΕΙΟΝ ΚΙΛΟΤΟ ΕΛΛΗΝΙΚΟ ΝΩΠΟ', nameGreek: 'ΒΟΕΙΟΝ ΚΙΛΟΤΟ ΕΛΛΗΝΙΚΟ ΝΩΠΟ', category: 'General', unit: 'kg' },
  { id: 'στηθοςλαπα-βοειου-γερμανιας-αο-τ-κ', name: 'ΣΤΗΘΟΣ-ΛΑΠΑ ΒΟΕΙΟΥ ΓΕΡΜΑΝΙΑΣ Α/Ο (Τ. Κ. )', nameGreek: 'ΣΤΗΘΟΣ-ΛΑΠΑ ΒΟΕΙΟΥ ΓΕΡΜΑΝΙΑΣ Α/Ο (Τ. Κ. )', category: 'General', unit: 'pcs' },
  { id: 'βοειον-λαπα-ελληνικο-νωπο', name: 'ΒΟΕΙΟΝ ΛΑΠΑ ΕΛΛΗΝΙΚΟ ΝΩΠΟ', nameGreek: 'ΒΟΕΙΟΝ ΛΑΠΑ ΕΛΛΗΝΙΚΟ ΝΩΠΟ', category: 'General', unit: 'pcs' },
  { id: 'ελια-βοειου-γερμανιας-νωπη-αοτιμ-κιλ', name: 'ΕΛΙΑ ΒΟΕΙΟΥ ΓΕΡΜΑΝΙΑΣ ΝΩΠΗ Α/Ο(ΤΙΜ. ΚΙΛ. )', nameGreek: 'ΕΛΙΑ ΒΟΕΙΟΥ ΓΕΡΜΑΝΙΑΣ ΝΩΠΗ Α/Ο(ΤΙΜ. ΚΙΛ. )', category: 'General', unit: 'pcs' },
  { id: 'βοειον-ελια-ελληνικο-αο-κιλονωπο', name: 'ΒΟΕΙΟΝ ΕΛΙΑ ΕΛΛΗΝΙΚΟ Α/Ο (ΚΙΛΟ)ΝΩΠΟ', nameGreek: 'ΒΟΕΙΟΝ ΕΛΙΑ ΕΛΛΗΝΙΚΟ Α/Ο (ΚΙΛΟ)ΝΩΠΟ', category: 'General', unit: 'kg' },
  { id: 'λεμονια-χυμα-εγχ-ποιοτητα-αtimh-κιλ', name: 'ΛΕΜΟΝΙΑ ΧΥΜΑ ΕΓΧ. ΠΟΙΟΤΗΤΑ Α\'(TIMH ΚΙΛ. )', nameGreek: 'ΛΕΜΟΝΙΑ ΧΥΜΑ ΕΓΧ. ΠΟΙΟΤΗΤΑ Α\'(TIMH ΚΙΛ. )', category: 'General', unit: 'pcs' },
  { id: 'πατατες-κρητης-διχτυκιλο', name: 'ΠΑΤΑΤΕΣ ΚΡΗΤΗΣ ΔΙΧΤΥ(ΚΙΛΟ)', nameGreek: 'ΠΑΤΑΤΕΣ ΚΡΗΤΗΣ ΔΙΧΤΥ(ΚΙΛΟ)', category: 'General', unit: 'kg' },
  { id: 'πατατες-φουρνου-διχτυ-ελλκιλο', name: 'ΠΑΤΑΤΕΣ ΦΟΥΡΝΟΥ ΔΙΧΤΥ ΕΛΛ(ΚΙΛΟ)', nameGreek: 'ΠΑΤΑΤΕΣ ΦΟΥΡΝΟΥ ΔΙΧΤΥ ΕΛΛ(ΚΙΛΟ)', category: 'General', unit: 'kg' },
  { id: 'πατατες-κυπρου-συςνες-ποιοτ-ατιμη-κιλ', name: 'ΠΑΤΑΤΕΣ ΚΥΠΡΟΥ ΣΥΣ/ΝΕΣ ΠΟΙΟΤ Α(ΤΙΜΗ ΚΙΛ)', nameGreek: 'ΠΑΤΑΤΕΣ ΚΥΠΡΟΥ ΣΥΣ/ΝΕΣ ΠΟΙΟΤ Α(ΤΙΜΗ ΚΙΛ)', category: 'General', unit: 'pcs' },
  { id: 'πατατες-χυμα-εις-ποιοτητα-α-τιμη-κιλ', name: 'ΠΑΤΑΤΕΣ ΧΥΜΑ ΕΙΣ. ΠΟΙΟΤΗΤΑ Α\' (ΤΙΜΗ ΚΙΛ. )', nameGreek: 'ΠΑΤΑΤΕΣ ΧΥΜΑ ΕΙΣ. ΠΟΙΟΤΗΤΑ Α\' (ΤΙΜΗ ΚΙΛ. )', category: 'General', unit: 'pcs' },
  { id: 'κρεμμυδια-ξερα-εις-ποιοτ-α-τιμη-κιλ', name: 'ΚΡΕΜΜΥΔΙΑ ΞΕΡΑ ΕΙΣ ΠΟΙΟΤ Α (ΤΙΜΗ ΚΙΛ. )', nameGreek: 'ΚΡΕΜΜΥΔΙΑ ΞΕΡΑ ΕΙΣ ΠΟΙΟΤ Α (ΤΙΜΗ ΚΙΛ. )', category: 'General', unit: 'pcs' },
  { id: 'κρεμm-ξερα-μετρια-εγχ-ποιοτ-α-τιμ-κιλ', name: 'ΚΡΕΜM ΞΕΡΑ ΜΕΤΡΙΑ ΕΓΧ ΠΟΙΟΤ. Α (ΤΙΜ ΚΙΛ. )', nameGreek: 'ΚΡΕΜM ΞΕΡΑ ΜΕΤΡΙΑ ΕΓΧ ΠΟΙΟΤ. Α (ΤΙΜ ΚΙΛ. )', category: 'General', unit: 'pcs' },
  { id: 'κρεμμυδια-ξερα-ξανθα-εις-ποιοτ-α-τκιλ', name: 'ΚΡΕΜΜΥΔΙΑ ΞΕΡΑ ΞΑΝΘΑ ΕΙΣ ΠΟΙΟΤ. Α (ΤΚΙΛ)', nameGreek: 'ΚΡΕΜΜΥΔΙΑ ΞΕΡΑ ΞΑΝΘΑ ΕΙΣ ΠΟΙΟΤ. Α (ΤΚΙΛ)', category: 'General', unit: 'pcs' },
  { id: 'κρεμμυδια-ξερα-ξανθα-εγχ-ποιοτ-α-τ-κιλ', name: 'ΚΡΕΜΜΥΔΙΑ ΞΕΡΑ ΞΑΝΘΑ ΕΓΧ ΠΟΙΟΤ Α (Τ. ΚΙΛ)', nameGreek: 'ΚΡΕΜΜΥΔΙΑ ΞΕΡΑ ΞΑΝΘΑ ΕΓΧ ΠΟΙΟΤ Α (Τ. ΚΙΛ)', category: 'General', unit: 'pcs' },
  { id: 'αχλαδια-κρυσταλια-lux-τιμη-κιλου', name: 'ΑΧΛΑΔΙΑ ΚΡΥΣΤΑΛΙΑ LUX (ΤΙΜΗ ΚΙΛΟΥ)', nameGreek: 'ΑΧΛΑΔΙΑ ΚΡΥΣΤΑΛΙΑ LUX (ΤΙΜΗ ΚΙΛΟΥ)', category: 'General', unit: 'kg' },
  // Beverages
  { id: 'λουμιδης-ελληνικος-καφες-μονοπ-15143g', name: 'ΛΟΥΜΙΔΗΣ ΕΛΛΗΝΙΚΟΣ ΚΑΦΕΣ ΜΟΝΟΠ 15/143G', nameGreek: 'ΛΟΥΜΙΔΗΣ ΕΛΛΗΝΙΚΟΣ ΚΑΦΕΣ ΜΟΝΟΠ 15/143G', category: 'Beverages', unit: 'pcs' },
  { id: 'zaros-νερο-1500ml-6αδα-pvc-φ', name: 'ZAROS ΝΕΡΟ 1500ML 6ΑΔΑ PVC (Φ)', nameGreek: 'ZAROS ΝΕΡΟ 1500ML 6ΑΔΑ PVC (Φ)', category: 'Beverages', unit: 'lt' },
  { id: 'κορπη-νερο-rpet-8χ500ml', name: 'ΚΟΡΠΗ ΝΕΡΟ RPET 8Χ500ML', nameGreek: 'ΚΟΡΠΗ ΝΕΡΟ RPET 8Χ500ML', category: 'Beverages', unit: 'lt' },
  // Vegetables
  { id: 'μελιτζανες-φλασκες-εισαγκιλο', name: 'ΜΕΛΙΤΖΑΝΕΣ ΦΛΑΣΚΕΣ ΕΙΣΑΓ(ΚΙΛΟ)', nameGreek: 'ΜΕΛΙΤΖΑΝΕΣ ΦΛΑΣΚΕΣ ΕΙΣΑΓ(ΚΙΛΟ)', category: 'Vegetables', unit: 'kg' },
  { id: 'μελιτζανα-φλασκα-εγχωρια-τιμη-κιλου', name: 'ΜΕΛΙΤΖΑΝΑ ΦΛΑΣΚΑ ΕΓΧΩΡΙΑ (ΤΙΜΗ ΚΙΛΟΥ)', nameGreek: 'ΜΕΛΙΤΖΑΝΑ ΦΛΑΣΚΑ ΕΓΧΩΡΙΑ (ΤΙΜΗ ΚΙΛΟΥ)', category: 'Vegetables', unit: 'kg' },
  // Fruits
  { id: 'αχλάδια-κρυσταλία-εις-εξτρα', name: 'Oil', nameGreek: 'ΑΧΛΆΔΙΑ ΚΡΥΣΤΑΛΊΑ ΕΙΣ ΕΞΤΡΑ', category: 'Fruits', unit: 'pcs' },
];

// Prices from e-Katanalotis (EUR)
export const prices: PriceEntry[] = [
  // ΠΙΝΔΟΣ ΚΟΤΟΠΟΥΛΟ ΕΛΛΗΝΙΚΟ ΝΩΠΟ(ΤΙΜ. ΚΙΛ)
  { productId: 'πινδος-κοτοπουλο-ελληνικο-νωποτιμ-κιλ', storeId: 'halkiadakis', price: 2.98, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'πινδος-κοτοπουλο-ελληνικο-νωποτιμ-κιλ', storeId: 'sklavenitis', price: 3, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'πινδος-κοτοπουλο-ελληνικο-νωποτιμ-κιλ', storeId: 'masoutis', price: 3.75, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'πινδος-κοτοπουλο-ελληνικο-νωποτιμ-κιλ', storeId: 'synka', price: 3.75, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'πινδος-κοτοπουλο-ελληνικο-νωποτιμ-κιλ', storeId: 'mymarket', price: 4.15, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΠΙΝΔΟΣ ΚΟΤΟΠ. ΕΛΛΗΝΙΚΑ ΝΩ Τ. 65% ΔΙΣΚ(Τ. Κ)
  { productId: 'πινδος-κοτοπ-ελληνικα-νω-τ-65-δισκτ-κ', storeId: 'marketin', price: 3.74, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'πινδος-κοτοπ-ελληνικα-νω-τ-65-δισκτ-κ', storeId: 'masoutis', price: 7.1, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'πινδος-κοτοπ-ελληνικα-νω-τ-65-δισκτ-κ', storeId: 'sklavenitis', price: 7.1, currency: 'EUR', lastUpdated: '2026-03-16' },
  // MIMIKOS ΚΟΤΟΠΟΥΛΟ ΕΛΛΗΝ. ΝΩΠΟ Τ. 65%(T. K)
  { productId: 'mimikos-κοτοπουλο-ελλην-νωπο-τ-65t-k', storeId: 'masoutis', price: 7.05, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'mimikos-κοτοπουλο-ελλην-νωπο-τ-65t-k', storeId: 'sklavenitis', price: 7.05, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'mimikos-κοτοπουλο-ελλην-νωπο-τ-65t-k', storeId: 'mymarket', price: 7.08, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'mimikos-κοτοπουλο-ελλην-νωπο-τ-65t-k', storeId: 'halkiadakis', price: 7.13, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΑΓΓΕΛΑΚΗΣ ΚΟΤΟΠ. ΕΛΛΗΝ. ΝΩΠΟ ΔΙΣΚ. (Τ. Κ)
  { productId: 'αγγελακης-κοτοπ-ελλην-νωπο-δισκ-τ-κ', storeId: 'sklavenitis', price: 3, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'αγγελακης-κοτοπ-ελλην-νωπο-δισκ-τ-κ', storeId: 'mymarket', price: 4.44, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΝΙΤΣΙΑΚΟΣ ΚΟΤ. ΕΛΛΗΝΙΚΑ ΝΩΠΑ ΔΙΣΚ(Τ. ΚΙΛ)
  { productId: 'νιτσιακος-κοτ-ελληνικα-νωπα-δισκτ-κιλ', storeId: 'masoutis', price: 2.99, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'νιτσιακος-κοτ-ελληνικα-νωπα-δισκτ-κιλ', storeId: 'sklavenitis', price: 4.9, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'νιτσιακος-κοτ-ελληνικα-νωπα-δισκτ-κιλ', storeId: 'mymarket', price: 5.18, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΠΙΝΔΟΣ ΦΙΛΕΤΟ ΣΤΗΘΟΣ ΚΟΤ. ΕΛΛ. ΝΩΠΟ (Τ. Κ. )
  { productId: 'πινδος-φιλετο-στηθος-κοτ-ελλ-νωπο-τ-κ', storeId: 'mymarket', price: 7.46, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'πινδος-φιλετο-στηθος-κοτ-ελλ-νωπο-τ-κ', storeId: 'halkiadakis', price: 9.85, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'πινδος-φιλετο-στηθος-κοτ-ελλ-νωπο-τ-κ', storeId: 'masoutis', price: 9.95, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'πινδος-φιλετο-στηθος-κοτ-ελλ-νωπο-τ-κ', storeId: 'sklavenitis', price: 9.95, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'πινδος-φιλετο-στηθος-κοτ-ελλ-νωπο-τ-κ', storeId: 'synka', price: 9.95, currency: 'EUR', lastUpdated: '2026-03-16' },
  // MIMIKOS ΣΤΗΘΟΣ ΦΙΛ. ΚΟΤ. ΕΛΛΗΝ. ΝΩΠΟ 650G
  { productId: 'mimikos-στηθος-φιλ-κοτ-ελλην-νωπο-650g', storeId: 'mymarket', price: 12.27, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'mimikos-στηθος-φιλ-κοτ-ελλην-νωπο-650g', storeId: 'masoutis', price: 12.3, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'mimikos-στηθος-φιλ-κοτ-ελλην-νωπο-650g', storeId: 'sklavenitis', price: 12.3, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'mimikos-στηθος-φιλ-κοτ-ελλην-νωπο-650g', storeId: 'halkiadakis', price: 13.18, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΑΡΝΙΑ ΕΛΛΗΝΙΚΑ (ΤIMH ΚΙΛΟY)
  { productId: 'αρνια-ελληνικα-τimh-κιλοy', storeId: 'mymarket', price: 13.79, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'αρνια-ελληνικα-τimh-κιλοy', storeId: 'masoutis', price: 13.8, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'αρνια-ελληνικα-τimh-κιλοy', storeId: 'sklavenitis', price: 13.8, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'αρνια-ελληνικα-τimh-κιλοy', storeId: 'synka', price: 13.8, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'αρνια-ελληνικα-τimh-κιλοy', storeId: 'halkiadakis', price: 13.8, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΚΑΤΣΙΚΙΑ ΕΛΛΗΝΙΚΑ (ΤIMH ΚΙΛΟY)
  { productId: 'κατσικια-ελληνικα-τimh-κιλοy', storeId: 'mymarket', price: 14.79, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'κατσικια-ελληνικα-τimh-κιλοy', storeId: 'masoutis', price: 14.8, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'κατσικια-ελληνικα-τimh-κιλοy', storeId: 'sklavenitis', price: 14.8, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'κατσικια-ελληνικα-τimh-κιλοy', storeId: 'halkiadakis', price: 14.8, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΜΠΡΙΖΟΛΑ ΧΟΙΡ. ΟΛΛΑΝΔ. ΝΩΠ. M/Ο X/Φ(Τ. Κ)
  { productId: 'μπριζολα-χοιρ-ολλανδ-νωπ-mο-xφτ-κ', storeId: 'marketin', price: 4.98, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'μπριζολα-χοιρ-ολλανδ-νωπ-mο-xφτ-κ', storeId: 'masoutis', price: 6.5, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'μπριζολα-χοιρ-ολλανδ-νωπ-mο-xφτ-κ', storeId: 'synka', price: 7.4, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'μπριζολα-χοιρ-ολλανδ-νωπ-mο-xφτ-κ', storeId: 'mymarket', price: 7.69, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'μπριζολα-χοιρ-ολλανδ-νωπ-mο-xφτ-κ', storeId: 'sklavenitis', price: 7.7, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΜΠΡΙΖΟΛΑ ΧΟΙΡ. ΕΛΛΗΝ. ΝΩΠΗ M/Ο Α/Δ Χ/Φ. Τ. Κ
  { productId: 'μπριζολα-χοιρ-ελλην-νωπη-mο-αδ-χφ-τ-κ', storeId: 'marketin', price: 4.98, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'μπριζολα-χοιρ-ελλην-νωπη-mο-αδ-χφ-τ-κ', storeId: 'masoutis', price: 4.99, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'μπριζολα-χοιρ-ελλην-νωπη-mο-αδ-χφ-τ-κ', storeId: 'halkiadakis', price: 7.15, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'μπριζολα-χοιρ-ελλην-νωπη-mο-αδ-χφ-τ-κ', storeId: 'sklavenitis', price: 7.4, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'μπριζολα-χοιρ-ελλην-νωπη-mο-αδ-χφ-τ-κ', storeId: 'synka', price: 7.45, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'μπριζολα-χοιρ-ελλην-νωπη-mο-αδ-χφ-τ-κ', storeId: 'mymarket', price: 7.99, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΧΟΙΡΙΝΟΣ ΛΑΙΜΟΣ ΟΛΛΑΝΔΙΑΣ Μ/Ο(ΤΙΜΗ ΚΙΛΟΥ
  { productId: 'χοιρινος-λαιμος-ολλανδιας-μοτιμη-κιλου', storeId: 'marketin', price: 5.29, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'χοιρινος-λαιμος-ολλανδιας-μοτιμη-κιλου', storeId: 'sklavenitis', price: 5.8, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'χοιρινος-λαιμος-ολλανδιας-μοτιμη-κιλου', storeId: 'halkiadakis', price: 6.9, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'χοιρινος-λαιμος-ολλανδιας-μοτιμη-κιλου', storeId: 'mymarket', price: 7.19, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'χοιρινος-λαιμος-ολλανδιας-μοτιμη-κιλου', storeId: 'masoutis', price: 7.2, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'χοιρινος-λαιμος-ολλανδιας-μοτιμη-κιλου', storeId: 'synka', price: 7.4, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΧΟΙΡΙΝΟΣ ΛΑΙΜΟΣ Μ/Ο ΕΛΛΗΝΙΚΟΣ(ΤΙΜΗ ΚΙΛ)
  { productId: 'χοιρινος-λαιμος-μο-ελληνικοςτιμη-κιλ', storeId: 'marketin', price: 5.29, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'χοιρινος-λαιμος-μο-ελληνικοςτιμη-κιλ', storeId: 'mymarket', price: 5.29, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'χοιρινος-λαιμος-μο-ελληνικοςτιμη-κιλ', storeId: 'masoutis', price: 7.4, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'χοιρινος-λαιμος-μο-ελληνικοςτιμη-κιλ', storeId: 'sklavenitis', price: 7.4, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'χοιρινος-λαιμος-μο-ελληνικοςτιμη-κιλ', storeId: 'synka', price: 7.4, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'χοιρινος-λαιμος-μο-ελληνικοςτιμη-κιλ', storeId: 'halkiadakis', price: 7.4, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΛΟΥΜΙΔΗΣ ΕΛΛΗΝΙΚΟΣ ΚΑΦΕΣ ΜΟΝΟΠ 15/143G
  { productId: 'λουμιδης-ελληνικος-καφες-μονοπ-15143g', storeId: 'galaxias', price: 3.96, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'λουμιδης-ελληνικος-καφες-μονοπ-15143g', storeId: 'masoutis', price: 3.96, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'λουμιδης-ελληνικος-καφες-μονοπ-15143g', storeId: 'ab', price: 4.28, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΛΟΥΜΙΔΗΣ ΠAΠAΓAΛOΣ ΠΑΡΑΔΟΣ 981Γ
  { productId: 'λουμιδης-πaπaγaλoς-παραδος-981γ', storeId: 'ab', price: 20.9, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'λουμιδης-πaπaγaλoς-παραδος-981γ', storeId: 'masoutis', price: 20.9, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΜΠΟΥΤΙ ΧΟΙΡ. ΟΛΛΑΝ. ΝΩΠΟ Α/Ο Α/Δ(Τ. Κ)
  { productId: 'μπουτι-χοιρ-ολλαν-νωπο-αο-αδτ-κ', storeId: 'marketin', price: 6.95, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'μπουτι-χοιρ-ολλαν-νωπο-αο-αδτ-κ', storeId: 'masoutis', price: 7.9, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'μπουτι-χοιρ-ολλαν-νωπο-αο-αδτ-κ', storeId: 'mymarket', price: 7.94, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'μπουτι-χοιρ-ολλαν-νωπο-αο-αδτ-κ', storeId: 'sklavenitis', price: 7.95, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΜΠΟΥΤΙ ΧΟΙΡ. ΕΛΛΗΝΙΚΟ ΝΩΠΟ Α/Ο(ΤΙΜΗ ΚΙΛ)
  { productId: 'μπουτι-χοιρ-ελληνικο-νωπο-αοτιμη-κιλ', storeId: 'synka', price: 5.8, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'μπουτι-χοιρ-ελληνικο-νωπο-αοτιμη-κιλ', storeId: 'halkiadakis', price: 7.6, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'μπουτι-χοιρ-ελληνικο-νωπο-αοτιμη-κιλ', storeId: 'masoutis', price: 7.95, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'μπουτι-χοιρ-ελληνικο-νωπο-αοτιμη-κιλ', storeId: 'sklavenitis', price: 7.95, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'μπουτι-χοιρ-ελληνικο-νωπο-αοτιμη-κιλ', storeId: 'marketin', price: 8.1, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'μπουτι-χοιρ-ελληνικο-νωπο-αοτιμη-κιλ', storeId: 'mymarket', price: 8.76, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΣΠΆΛΑ ΝΕΑΡΟΎ ΜΟΣΧ Α/Ο ΝΩΠΉ ΕΙΣ
  { productId: 'σπάλα-νεαρού-μοσχ-αο-νωπή-εις', storeId: 'sklavenitis', price: 16.9, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'σπάλα-νεαρού-μοσχ-αο-νωπή-εις', storeId: 'mymarket', price: 18.39, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΣΠΑΛΑ ΒΟΕΙΟΥ ΓΕΡΜΑΝ. ΝΩΠΗ Α/Ο (ΤΙΜ. ΚΙΛ).
  { productId: 'σπαλα-βοειου-γερμαν-νωπη-αο-τιμ-κιλ', storeId: 'synka', price: 14.9, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'σπαλα-βοειου-γερμαν-νωπη-αο-τιμ-κιλ', storeId: 'masoutis', price: 16.4, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'σπαλα-βοειου-γερμαν-νωπη-αο-τιμ-κιλ', storeId: 'marketin', price: 16.85, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'σπαλα-βοειου-γερμαν-νωπη-αο-τιμ-κιλ', storeId: 'mymarket', price: 16.89, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΒΟΕΙΟΝ ΣΠΑΛΑ ΕΛΛΗΝΙΚΟ Α/Ο(ΚΙΛΟ)ΝΩΠΟ
  { productId: 'βοειον-σπαλα-ελληνικο-αοκιλονωπο', storeId: 'masoutis', price: 16.4, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'βοειον-σπαλα-ελληνικο-αοκιλονωπο', storeId: 'sklavenitis', price: 16.9, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'βοειον-σπαλα-ελληνικο-αοκιλονωπο', storeId: 'halkiadakis', price: 16.9, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'βοειον-σπαλα-ελληνικο-αοκιλονωπο', storeId: 'synka', price: 16.98, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΚΙΛΟΤΟ ΜΟΣΧΟΥ ΓΑΛΑΚΤΟΣ ΟΛΛΑΝΔΙΑΣ Τ. Κ.
  { productId: 'κιλοτο-μοσχου-γαλακτος-ολλανδιας-τ-κ', storeId: 'sklavenitis', price: 17.9, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΚΙΛΟΤΟ ΒΟΕΙΟΥ ΓΕΡΜΑΝΙΑΣ ΝΩΠΟ Α/Ο(Τ. ΚΙΛ)
  { productId: 'κιλοτο-βοειου-γερμανιας-νωπο-αοτ-κιλ', storeId: 'marketin', price: 16.9, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'κιλοτο-βοειου-γερμανιας-νωπο-αοτ-κιλ', storeId: 'masoutis', price: 17.4, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΒΟΕΙΟΝ ΚΙΛΟΤΟ ΕΛΛΗΝΙΚΟ ΝΩΠΟ
  { productId: 'βοειον-κιλοτο-ελληνικο-νωπο', storeId: 'masoutis', price: 17.4, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'βοειον-κιλοτο-ελληνικο-νωπο', storeId: 'halkiadakis', price: 17.6, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'βοειον-κιλοτο-ελληνικο-νωπο', storeId: 'sklavenitis', price: 17.9, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'βοειον-κιλοτο-ελληνικο-νωπο', storeId: 'synka', price: 17.9, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΛΆΠΑ ΝΕΑΡΟΎ ΜΟΣΧ Α/Ο ΝΩΠΉ ΕΙΣ
  { productId: 'λάπα-νεαρού-μοσχ-αο-νωπή-εις', storeId: 'sklavenitis', price: 13.2, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΣΤΗΘΟΣ-ΛΑΠΑ ΒΟΕΙΟΥ ΓΕΡΜΑΝΙΑΣ Α/Ο (Τ. Κ. )
  { productId: 'στηθοςλαπα-βοειου-γερμανιας-αο-τ-κ', storeId: 'synka', price: 13.2, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'στηθοςλαπα-βοειου-γερμανιας-αο-τ-κ', storeId: 'mymarket', price: 13.29, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'στηθοςλαπα-βοειου-γερμανιας-αο-τ-κ', storeId: 'marketin', price: 13.65, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΒΟΕΙΟΝ ΛΑΠΑ ΕΛΛΗΝΙΚΟ ΝΩΠΟ
  { productId: 'βοειον-λαπα-ελληνικο-νωπο', storeId: 'synka', price: 13.2, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΕΛΙΆ ΝΕΑΡΟΎ ΜΟΣΧ Α/Ο ΝΩΠΉ ΕΙΣ
  { productId: 'ελιά-νεαρού-μοσχ-αο-νωπή-εις', storeId: 'sklavenitis', price: 16.9, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'ελιά-νεαρού-μοσχ-αο-νωπή-εις', storeId: 'mymarket', price: 18.79, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΕΛΙΑ ΒΟΕΙΟΥ ΓΕΡΜΑΝΙΑΣ ΝΩΠΗ Α/Ο(ΤΙΜ. ΚΙΛ. )
  { productId: 'ελια-βοειου-γερμανιας-νωπη-αοτιμ-κιλ', storeId: 'masoutis', price: 16.4, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'ελια-βοειου-γερμανιας-νωπη-αοτιμ-κιλ', storeId: 'marketin', price: 16.85, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'ελια-βοειου-γερμανιας-νωπη-αοτιμ-κιλ', storeId: 'mymarket', price: 16.89, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'ελια-βοειου-γερμανιας-νωπη-αοτιμ-κιλ', storeId: 'synka', price: 16.9, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΒΟΕΙΟΝ ΕΛΙΑ ΕΛΛΗΝΙΚΟ Α/Ο (ΚΙΛΟ)ΝΩΠΟ
  { productId: 'βοειον-ελια-ελληνικο-αο-κιλονωπο', storeId: 'masoutis', price: 16.4, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'βοειον-ελια-ελληνικο-αο-κιλονωπο', storeId: 'sklavenitis', price: 16.9, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'βοειον-ελια-ελληνικο-αο-κιλονωπο', storeId: 'halkiadakis', price: 16.9, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'βοειον-ελια-ελληνικο-αο-κιλονωπο', storeId: 'synka', price: 16.98, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΜΕΛΙΤΖΑΝΕΣ ΦΛΑΣΚΕΣ ΕΙΣΑΓ(ΚΙΛΟ)
  { productId: 'μελιτζανες-φλασκες-εισαγκιλο', storeId: 'masoutis', price: 2.58, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΜΕΛΙΤΖΑΝΑ ΦΛΑΣΚΑ ΕΓΧΩΡΙΑ (ΤΙΜΗ ΚΙΛΟΥ)
  { productId: 'μελιτζανα-φλασκα-εγχωρια-τιμη-κιλου', storeId: 'synka', price: 3.65, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'μελιτζανα-φλασκα-εγχωρια-τιμη-κιλου', storeId: 'halkiadakis', price: 3.65, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'μελιτζανα-φλασκα-εγχωρια-τιμη-κιλου', storeId: 'masoutis', price: 3.9, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'μελιτζανα-φλασκα-εγχωρια-τιμη-κιλου', storeId: 'sklavenitis', price: 3.9, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'μελιτζανα-φλασκα-εγχωρια-τιμη-κιλου', storeId: 'marketin', price: 4.39, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'μελιτζανα-φλασκα-εγχωρια-τιμη-κιλου', storeId: 'mymarket', price: 4.59, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΛΕΜΟΝΙΑ ΧΥΜΑ ΕΓΧ. ΠΟΙΟΤΗΤΑ Α'(TIMH ΚΙΛ. )
  { productId: 'λεμονια-χυμα-εγχ-ποιοτητα-αtimh-κιλ', storeId: 'halkiadakis', price: 1.15, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'λεμονια-χυμα-εγχ-ποιοτητα-αtimh-κιλ', storeId: 'synka', price: 1.49, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'λεμονια-χυμα-εγχ-ποιοτητα-αtimh-κιλ', storeId: 'sklavenitis', price: 1.6, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'λεμονια-χυμα-εγχ-ποιοτητα-αtimh-κιλ', storeId: 'marketin', price: 1.79, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'λεμονια-χυμα-εγχ-ποιοτητα-αtimh-κιλ', storeId: 'masoutis', price: 1.85, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'λεμονια-χυμα-εγχ-ποιοτητα-αtimh-κιλ', storeId: 'mymarket', price: 1.89, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ZAROS ΝΕΡΟ 1500ML 6ΑΔΑ PVC (Φ)
  { productId: 'zaros-νερο-1500ml-6αδα-pvc-φ', storeId: 'sklavenitis', price: 1.85, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'zaros-νερο-1500ml-6αδα-pvc-φ', storeId: 'masoutis', price: 2.1, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'zaros-νερο-1500ml-6αδα-pvc-φ', storeId: 'synka', price: 2.49, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΠΑΤΑΤΕΣ ΚΡΗΤΗΣ ΔΙΧΤΥ(ΚΙΛΟ)
  { productId: 'πατατες-κρητης-διχτυκιλο', storeId: 'sklavenitis', price: 0.65, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'πατατες-κρητης-διχτυκιλο', storeId: 'mymarket', price: 0.8, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'πατατες-κρητης-διχτυκιλο', storeId: 'masoutis', price: 0.85, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'πατατες-κρητης-διχτυκιλο', storeId: 'synka', price: 0.95, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'πατατες-κρητης-διχτυκιλο', storeId: 'halkiadakis', price: 0.98, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΠΑΤΑΤΕΣ ΦΟΥΡΝΟΥ ΔΙΧΤΥ ΕΛΛ(ΚΙΛΟ)
  { productId: 'πατατες-φουρνου-διχτυ-ελλκιλο', storeId: 'synka', price: 0.65, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'πατατες-φουρνου-διχτυ-ελλκιλο', storeId: 'halkiadakis', price: 0.65, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'πατατες-φουρνου-διχτυ-ελλκιλο', storeId: 'masoutis', price: 0.85, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'πατατες-φουρνου-διχτυ-ελλκιλο', storeId: 'efresh', price: 1.08, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΠΑΤΑΤΕΣ ΚΥΠΡΟΥ ΣΥΣ/ΝΕΣ ΠΟΙΟΤ Α(ΤΙΜΗ ΚΙΛ)
  { productId: 'πατατες-κυπρου-συςνες-ποιοτ-ατιμη-κιλ', storeId: 'halkiadakis', price: 1.48, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'πατατες-κυπρου-συςνες-ποιοτ-ατιμη-κιλ', storeId: 'mymarket', price: 1.49, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'πατατες-κυπρου-συςνες-ποιοτ-ατιμη-κιλ', storeId: 'synka', price: 1.53, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'πατατες-κυπρου-συςνες-ποιοτ-ατιμη-κιλ', storeId: 'efresh', price: 1.55, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'πατατες-κυπρου-συςνες-ποιοτ-ατιμη-κιλ', storeId: 'marketin', price: 1.55, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'πατατες-κυπρου-συςνες-ποιοτ-ατιμη-κιλ', storeId: 'masoutis', price: 1.55, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'πατατες-κυπρου-συςνες-ποιοτ-ατιμη-κιλ', storeId: 'sklavenitis', price: 1.55, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΠΑΤΑΤΕΣ ΧΥΜΑ ΕΙΣ. ΠΟΙΟΤΗΤΑ Α' (ΤΙΜΗ ΚΙΛ. )
  { productId: 'πατατες-χυμα-εις-ποιοτητα-α-τιμη-κιλ', storeId: 'sklavenitis', price: 0.65, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'πατατες-χυμα-εις-ποιοτητα-α-τιμη-κιλ', storeId: 'marketin', price: 0.69, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'πατατες-χυμα-εις-ποιοτητα-α-τιμη-κιλ', storeId: 'masoutis', price: 0.75, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'πατατες-χυμα-εις-ποιοτητα-α-τιμη-κιλ', storeId: 'halkiadakis', price: 0.78, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'πατατες-χυμα-εις-ποιοτητα-α-τιμη-κιλ', storeId: 'synka', price: 0.79, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΚΡΕΜΜΥΔΙΑ ΞΕΡΑ ΕΙΣ ΠΟΙΟΤ Α (ΤΙΜΗ ΚΙΛ. )
  { productId: 'κρεμμυδια-ξερα-εις-ποιοτ-α-τιμη-κιλ', storeId: 'sklavenitis', price: 0.9, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'κρεμμυδια-ξερα-εις-ποιοτ-α-τιμη-κιλ', storeId: 'synka', price: 0.98, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'κρεμμυδια-ξερα-εις-ποιοτ-α-τιμη-κιλ', storeId: 'efresh', price: 1.09, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'κρεμμυδια-ξερα-εις-ποιοτ-α-τιμη-κιλ', storeId: 'masoutis', price: 1.28, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΚΡΕΜM ΞΕΡΑ ΜΕΤΡΙΑ ΕΓΧ ΠΟΙΟΤ. Α (ΤΙΜ ΚΙΛ. )
  { productId: 'κρεμm-ξερα-μετρια-εγχ-ποιοτ-α-τιμ-κιλ', storeId: 'marketin', price: 0.59, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'κρεμm-ξερα-μετρια-εγχ-ποιοτ-α-τιμ-κιλ', storeId: 'synka', price: 0.88, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'κρεμm-ξερα-μετρια-εγχ-ποιοτ-α-τιμ-κιλ', storeId: 'halkiadakis', price: 0.88, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'κρεμm-ξερα-μετρια-εγχ-ποιοτ-α-τιμ-κιλ', storeId: 'masoutis', price: 0.9, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'κρεμm-ξερα-μετρια-εγχ-ποιοτ-α-τιμ-κιλ', storeId: 'mymarket', price: 0.9, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'κρεμm-ξερα-μετρια-εγχ-ποιοτ-α-τιμ-κιλ', storeId: 'sklavenitis', price: 0.9, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'κρεμm-ξερα-μετρια-εγχ-ποιοτ-α-τιμ-κιλ', storeId: 'efresh', price: 1.05, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΚΡΕΜΜΥΔΙΑ ΞΕΡΑ ΞΑΝΘΑ ΕΙΣ ΠΟΙΟΤ. Α (ΤΚΙΛ)
  { productId: 'κρεμμυδια-ξερα-ξανθα-εις-ποιοτ-α-τκιλ', storeId: 'sklavenitis', price: 0.9, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'κρεμμυδια-ξερα-ξανθα-εις-ποιοτ-α-τκιλ', storeId: 'efresh', price: 0.95, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'κρεμμυδια-ξερα-ξανθα-εις-ποιοτ-α-τκιλ', storeId: 'masoutis', price: 0.97, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'κρεμμυδια-ξερα-ξανθα-εις-ποιοτ-α-τκιλ', storeId: 'halkiadakis', price: 1.08, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΚΡΕΜΜΥΔΙΑ ΞΕΡΑ ΞΑΝΘΑ ΕΓΧ ΠΟΙΟΤ Α (Τ. ΚΙΛ)
  { productId: 'κρεμμυδια-ξερα-ξανθα-εγχ-ποιοτ-α-τ-κιλ', storeId: 'halkiadakis', price: 0.88, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'κρεμμυδια-ξερα-ξανθα-εγχ-ποιοτ-α-τ-κιλ', storeId: 'masoutis', price: 0.9, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'κρεμμυδια-ξερα-ξανθα-εγχ-ποιοτ-α-τ-κιλ', storeId: 'mymarket', price: 0.9, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'κρεμμυδια-ξερα-ξανθα-εγχ-ποιοτ-α-τ-κιλ', storeId: 'sklavenitis', price: 0.9, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'κρεμμυδια-ξερα-ξανθα-εγχ-ποιοτ-α-τ-κιλ', storeId: 'efresh', price: 1.05, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΚΟΡΠΗ ΝΕΡΟ RPET 8Χ500ML
  { productId: 'κορπη-νερο-rpet-8χ500ml', storeId: 'galaxias', price: 1.96, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'κορπη-νερο-rpet-8χ500ml', storeId: 'ab', price: 2.14, currency: 'EUR', lastUpdated: '2026-03-16' },
  // ΑΧΛΑΔΙΑ ΚΡΥΣΤΑΛΙΑ LUX (ΤΙΜΗ ΚΙΛΟΥ)
  { productId: 'αχλαδια-κρυσταλια-lux-τιμη-κιλου', storeId: 'marketin', price: 2.4, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'αχλαδια-κρυσταλια-lux-τιμη-κιλου', storeId: 'masoutis', price: 2.4, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'αχλαδια-κρυσταλια-lux-τιμη-κιλου', storeId: 'sklavenitis', price: 2.4, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'αχλαδια-κρυσταλια-lux-τιμη-κιλου', storeId: 'halkiadakis', price: 2.45, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'αχλαδια-κρυσταλια-lux-τιμη-κιλου', storeId: 'synka', price: 2.49, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'αχλαδια-κρυσταλια-lux-τιμη-κιλου', storeId: 'mymarket', price: 3.09, currency: 'EUR', lastUpdated: '2026-03-16' },
  { productId: 'αχλαδια-κρυσταλια-lux-τιμη-κιλου', storeId: 'efresh', price: 3.36, currency: 'EUR', lastUpdated: '2026-03-16' },
  // Oil
  { productId: 'αχλάδια-κρυσταλία-εις-εξτρα', storeId: 'masoutis', price: 2.98, currency: 'EUR', lastUpdated: '2026-03-16' },
];

// Helper functions
export function getProductById(id: string): Product | undefined {
  return products.find(p => p.id === id);
}

export function getStoreById(id: string): Store | undefined {
  return stores.find(s => s.id === id);
}

export function getPricesForProduct(productId: string): PriceEntry[] {
  return prices.filter(p => p.productId === productId);
}

export function findCheapestPrice(productId: string): PriceEntry | undefined {
  const productPrices = getPricesForProduct(productId);
  return productPrices.reduce((min, p) => p.price < min.price ? p : min, productPrices[0]);
}
